### ISSUE TITLE
neucoind crashes if debug, printcoinage is 1, on Linux

### ISSUE THREAD

**Issue by redfish64** [NeuCoin/neucoin#11]
If the following are specified in the neucoin.conf file:

debug=1
printcoinage=1

neucoind and neucoin-qt will segfault.

I found the issue, below is the patch. The linux version of printf doesn't understand "%-12I64d", so it just skips it. Because so, there are now only two read "%" items in the string, yet 3 var args.

```
index 8e0a13f..520dde5 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -1769,7 +1769,7 @@ bool CTransaction::GetCoinAge(CTxDB& txdb, uint64& nCoinAge, bool ignoreStakeAge
         bnCentSecond += CBigNum(nValueIn) * (nTime-txPrev.nTime) / CENT;

         if (fDebug && GetBoolArg("-printcoinage"))
-            printf("coin age nValueIn=%-12I64d nTimeDiff=%d bnCentSecond=%s\n", nValueIn, nTime - txPrev.nTime, bnCentSecond.ToString().c_str());
+         printf("coin age nValueIn=%ld nTimeDiff=%d bnCentSecond=%s\n", (long)nValueIn, nTime - txPrev.nTime, bnCentSecond.ToString().c_str());
     }

     CBigNum bnCoinDay = bnCentSecond * CENT / COIN / (24 * 60 * 60);
```

**Comment by arcanis** [comment]
I can't reproduce this error but I can see it in the code you've linked.

The issue isn't so much that there is too many var_args - excedentary ones are just ignored -, but rather that in this case, since the `%-12I64d` is invalid, the `%s` format will be fed with a basic integer instead of a string pointer. So once printf tries to dereference the "pointer" to access the memory, it will crash and burn (and segfault).

Thanks for the investigation,
