### ISSUE TITLE
"Warning: No sync-checkpoint received for quite a long time"

### ISSUE THREAD

**Issue by nemecis1000** [NeuCoin/neucoin#19]
according saw in a comment does not affect but in reality if it is assumed that the stake lasts 1.6 days? I have four good days with the message on my client QT and no stake, look ua quick fix to this but the network will be vunerable and nobody will want to stake

**Comment by arcanis** [comment]
I'm sorry but I'm not sure I have correctly understood your issue. If it's about the warning, as your title suggests, then it's right, it's not an issue. It only means that we didn't published sync-checkpoints yet.

Sync-checkpoints are a PoS feature that allow the coin operators to manually enforce a blockchain if need be. Since this feature is by nature quite centralizing, we promised to not use it until its usefulness exceed its drawback.

Closing for now. Feel free to comment if I've answered the wrong question.
